version: 2
jobs:
  # job name is "one:"
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello, job one"
      # comment below to break build
      #- run: notacommand
 
 # job name is "two:"
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi, job two"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
